logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "universal"
build-mode = "module"
included-patches = "copy-video-url disable-shorts-on-startup disable-auto-captions disable-zoom-haptics hide-ads minimized-playback old-video-quality-menu open-links-externally premium-heading remember-video-quality return-youtube-dislike seekbar-tapping sponsorblock video-ads"
exclusive-patches = true
