enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
version = "auto"
included-patches = "'Copy video URL' 'Seekbar tapping' 'External downloads' 'Hide ads' 'Video ads' 'Spoof device dimensions' 'Minimized playback' 'Remove tracking query parameter' 'Enable debugging' 'Client spoof' 'Disable zoom haptics' 'Announcements' 'Bypass URL redirects' 'Return YouTube Dislike' 'Disable auto captions' 'SponsorBlock' 'Disable resuming Shorts on startup' 'Custom branding' 'Restore old video quality menu' 'Remember video quality'"
exclusive-patches = true

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
included-patches = "'Downloads' 'Remember clear display'"
exclusive-patches = true

[com.ss.android.ugc.trill]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
included-patches = "'Downloads' 'Remember clear display'"
exclusive-patches = true

